### ISSUE TITLE
Redundant space 🐛 

### ISSUE THREAD

**Issue by kom-a** [kom-a/KR580VM80A#4]
There is one redundant space character before digit in some instructions like
`MVI D,  00`
`CPI  02`
`XRI  FF`

**Comment by kom-a** [comment]
This comes out when disassembling

**Comment by en9er** [comment]
done

**Comment by en9er** [comment]
fixed in 
https://github.com/en9er/kr580/commit/05b339caf7a619ce725f56917a183113ba736d
